### ISSUE TITLE
Update to Falco 0.14

### ISSUE THREAD

**Issue by nestorsalceda** [falcosecurity-retire/falco-operator#5]
A new release of Falco happened a few days ago. The Helm chart will be bumped in a few days and then, we should use the latest version of Falco.

Thanks!

**Comment by sbkg0002** [comment]
This would be great. @nestorsalceda did you try to rebuild the container image and bump the falco base version?

**Comment by mumoshu** [comment]
Bumped falco in #7. But not sure if it actually works as we don't have CI set up yet!

I'll create a dedicated issue to track efforts for CI
